#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Minesweeper.Resource", IsApplication=true)]

namespace Minesweeper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int boom = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flag = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int m = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int m1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int m2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int m3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int m4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int m5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int mine = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mine1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int mine2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mine3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int mine4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sample = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int smiley = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int smiley1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int smiley2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int smiley3 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int tile = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tile2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int tile3 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int tile4 = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int button1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int gridView1 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int tableLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int tableRow1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int btn = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
